//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopERP.Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    /// <summary>
    /// Defines the <see cref="ERPDBEntities" />.
    /// </summary>
    public partial class ERPDBEntities : DbContext
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ERPDBEntities"/> class.
        /// </summary>
        public ERPDBEntities()
            : base("name=ERPDBEntities")
        {
        }

        /// <summary>
        /// The OnModelCreating.
        /// </summary>
        /// <param name="modelBuilder">The modelBuilder<see cref="DbModelBuilder"/>.</param>
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        /// <summary>
        /// Gets or sets the Inventory.
        /// </summary>
        public virtual DbSet<Inventory> Inventory { get; set; }

        /// <summary>
        /// Gets or sets the Staff.
        /// </summary>
        public virtual DbSet<Staff> Staff { get; set; }

        /// <summary>
        /// Gets or sets the schedule.
        /// </summary>
        public virtual DbSet<schedule> schedule { get; set; }

        /// <summary>
        /// Gets or sets the WorkTime.
        /// </summary>
        public virtual DbSet<WorkTime> WorkTime { get; set; }

        /// <summary>
        /// Gets or sets the Product.
        /// </summary>
        public virtual DbSet<Product> Product { get; set; }

        /// <summary>
        /// Gets or sets the Sell_Record.
        /// </summary>
        public virtual DbSet<Sell_Record> Sell_Record { get; set; }

        /// <summary>
        /// Gets or sets the Staff_Auth.
        /// </summary>
        public virtual DbSet<Staff_Auth> Staff_Auth { get; set; }
    }
}
