//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopERP.Models
{
    /// <summary>
    /// Defines the <see cref="Sell_Record" />.
    /// </summary>
    public partial class Sell_Record
    {
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        public int id { get; set; }

        /// <summary>
        /// Gets or sets the product_id.
        /// </summary>
        public string product_id { get; set; }

        /// <summary>
        /// Gets or sets the product_name.
        /// </summary>
        public string product_name { get; set; }

        /// <summary>
        /// Gets or sets the delivery_count.
        /// </summary>
        public int delivery_count { get; set; }

        /// <summary>
        /// Gets or sets the sell_count.
        /// </summary>
        public int sell_count { get; set; }

        /// <summary>
        /// Gets or sets the trash_count.
        /// </summary>
        public int trash_count { get; set; }

        /// <summary>
        /// Gets or sets the create_time.
        /// </summary>
        public System.DateTime create_time { get; set; }

        /// <summary>
        /// Gets or sets the update_time.
        /// </summary>
        public System.DateTime update_time { get; set; }
    }
}
